### ISSUE TITLE
Contribute for Hacktoberfest 2020

### ISSUE THREAD

**Issue by srinibasbiswal** [srinibasbiswal/Github-Profile-README#24]
If this is your first pull request, please read this article: [How To Create a Pull Request on GitHub](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github)

Read more about GitHub Profile README: [GitHub Official Profile README Docs](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/managing-your-profile-readme)

### Step 1

Fork the repo by pressing the "Fork" button on the top right side of the
repository and clone your forked repository.

### Step 2

In your forked repository, edit `users.js` [(src/dataSet/users.js)](src/dataSet/users.js) and add your name and github userName to the bottom of the file using this format:

```
  {
    name : "Full Name",
    github : "github userName"
  }
```

### Step 3 

In your forked repository, go to `githubCards folder` [(src/dataSet/githubCards)](src/dataSet/githubCards) and add you Github Profile README template keeping the name of the file as your `github userName` with extension as `.md`.

```
Example : 
if GitHub userName is srinibasbiswal, then the fileName will be :

srinibasbiswal.md

```

### Step 4 

Commit your changes and submit a pull request! After your pull request gets accepted, you will be able to see your very own GitHub README card on the [Github Profile READMEs](https://github-profile-readmes.firebaseapp.com/)!

**Comment by shin-iji** [comment]
@srinibasbiswal can i do this?

**Comment by srinibasbiswal** [comment]
@shin-iji sure.

**Comment by ankitaugale23** [comment]
Can I do this?

**Comment by srinibasbiswal** [comment]
sure @ankitaugale23

**Comment by meghasharma123** [comment]
I had done this Please add my request.

**Comment by srinibasbiswal** [comment]
merged @meghasharma123 . Thanks for contributing.

**Comment by meghasharma123** [comment]
Thank you so much..:)

**Comment by Vrindagupta6828** [comment]
@srinibasbiswal  I have done a PR please merge it.. #62

**Comment by srinibasbiswal** [comment]
Thank you everyone for contributing.  ✌ 🔥
